FROM python:3.12
WORKDIR /app
COPY . /app/
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-root --no-cache --no-interaction
EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "fastapi_project.main:app", "--host", "0.0.0.0"]
